# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-02-24 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bounce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sns_topic', models.CharField(max_length=350)),
                ('sns_message_id', models.CharField(max_length=100)),
                ('mail_timestamp', models.DateTimeField()),
                ('mail_id', models.CharField(max_length=100)),
                ('mail_from', models.EmailField(max_length=254)),
                ('address', models.EmailField(max_length=254)),
                ('feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Feedback Time')),
                ('hard', models.BooleanField(db_index=True, verbose_name='Hard Bounce')),
                ('bounce_type', models.CharField(db_index=True, max_length=50, verbose_name='Bounce Type')),
                ('bounce_subtype', models.CharField(db_index=True, max_length=50, verbose_name='Bounce SubType')),
                ('reporting_mta', models.TextField(blank=True, null=True)),
                ('action', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Action')),
                ('status', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('diagnostic_code', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sns_topic', models.CharField(max_length=350)),
                ('sns_message_id', models.CharField(max_length=100)),
                ('mail_timestamp', models.DateTimeField()),
                ('mail_id', models.CharField(max_length=100)),
                ('mail_from', models.EmailField(max_length=254)),
                ('address', models.EmailField(max_length=254)),
                ('feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Feedback Time')),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('feedback_type', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Complaint Type')),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
