# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-02-24 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounce',
            old_name='feedback',
            new_name='feedback_id',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='feedback',
            new_name='feedback_id',
        ),
    ]
