# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-02-24 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_auto_20200224_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounce',
            name='sns_message_id',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='sns_message_id',
        ),
    ]
