# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-02-24 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_auto_20200224_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounce',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
