# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-26 11:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20180726_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='subject',
            field=models.TextField(max_length=998, null=True),
        ),
    ]
