# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-26 15:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_recipientgroup_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientgroup',
            name='preview',
            field=models.BooleanField(default=False, help_text=b'Specify whether this group should be used for organizing recipients of preview emails. Leave unchecked if this group contains/will contain recipients for live emails.', verbose_name=b'Is a Preview Group'),
        ),
    ]
