# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-27 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_instance_subject'),
        ('manager', '0009_auto_20180726_1551'),
    ]

    operations = [
    ]
