# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-17 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_merge_20180727_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubprocessStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit_name', models.CharField(max_length=200)),
                ('current_unit', models.IntegerField()),
                ('total_units', models.IntegerField()),
                ('error', models.CharField(max_length=1000)),
            ],
        ),
    ]
