# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-28 10:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_subprocessstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprocessstatus',
            name='success_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
