# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-28 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_subprocessstatus_success_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprocessstatus',
            name='back_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
