# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-07-02 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_remove_instance_litmus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientgroup',
            name='description',
            field=models.TextField(blank=True, help_text=b'Details about this recipient group for internal reference, such as specific details about included recipients, frequency of imported data, etc.', null=True),
        ),
    ]
