# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-08-27 10:15


from django.db import migrations, models
import util


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_recipientgroup_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removal_hash', models.CharField(max_length=56)),
                ('instances', models.ManyToManyField(default=util.create_hash, related_name='stale_record', to='manager.Instance')),
            ],
        ),
    ]
