# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-09-09 23:23


from django.db import migrations, models
import util


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_stalerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stalerecord',
            name='instances',
            field=models.ManyToManyField(related_name='stale_record', to='manager.Instance'),
        ),
        migrations.AlterField(
            model_name='stalerecord',
            name='removal_hash',
            field=models.CharField(default=util.create_hash, max_length=56),
        ),
    ]
