# Generated by Django 3.1.1 on 2020-10-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20200917_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='success',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
