# Generated by Django 3.1.1 on 2021-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_auto_20201005_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewinstance',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
