# Generated by Django 3.1.12 on 2021-09-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_auto_20210827_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('in_recipient_group', 'In recipient group'), ('has_attribute', 'Has attribute'), ('received_email', 'Received email'), ('opened_email', 'Opened email'), ('clicked_link', 'Clicked on URL'), ('clicked_any_url_in_email', 'Click on any url in instance')], max_length=40)),
                ('conditional', models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR')], max_length=3, null=True)),
                ('value', models.CharField(max_length=255)),
                ('group', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Details about this recipient group for internal reference, such as specific details about included recipients, frequency of imported data, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('preview', models.BooleanField(default=False, help_text='Specify whether this group should be used for organizing recipients of preview emails. Leave unchecked if this group contains/will contain recipients for live emails.', verbose_name='Is a Preview Group')),
                ('exclude_rules', models.ManyToManyField(blank=True, related_name='exclude_segments', to='manager.SegmentRule')),
                ('include_rules', models.ManyToManyField(related_name='include_segments', to='manager.SegmentRule')),
            ],
        ),
    ]
