# Generated by Django 3.1.12 on 2021-09-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_segment_segmentrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentrule',
            name='key',
            field=models.CharField(blank=True, help_text='The key within a key/value pair lookup', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segmentrule',
            name='field',
            field=models.CharField(choices=[('in_recipient_group', 'In recipient group'), ('has_attribute', 'Has attribute'), ('received_email', 'Received email'), ('opened_email', 'Opened email'), ('opened_instance', 'Opened instance'), ('clicked_link', 'Clicked on URL'), ('clicked_any_url_in_email', 'Click on any url in instance')], max_length=40),
        ),
        migrations.AlterField(
            model_name='segmentrule',
            name='value',
            field=models.CharField(help_text='The value which to filter the segment by', max_length=255),
        ),
    ]
