# Generated by Django 3.1.12 on 2021-09-08 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_auto_20210907_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='exclude_rules',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='include_rules',
        ),
        migrations.AddField(
            model_name='segmentrule',
            name='rule_type',
            field=models.CharField(choices=[('include', 'Include'), ('exclude', 'Exclude')], default='include', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segmentrule',
            name='segment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='manager.segment'),
            preserve_default=False,
        ),
    ]
