# Generated by Django 3.1.12 on 2021-09-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_auto_20210908_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='description',
            field=models.TextField(blank=True, help_text='Details about this segment for internal reference, such as specific details about included recipients, frequency of imported data, etc.', null=True),
        ),
    ]
