# Generated by Django 3.1.12 on 2021-09-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_auto_20210915_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='segments',
            field=models.ManyToManyField(blank=True, help_text='Which segment(s) this email will go to.', related_name='emails', to='manager.Segment'),
        ),
        migrations.AlterField(
            model_name='email',
            name='recipient_groups',
            field=models.ManyToManyField(blank=True, help_text='Which group(s) of recipients this email will go to.', related_name='emails', to='manager.RecipientGroup'),
        ),
        migrations.AddConstraint(
            model_name='email',
            constraint=models.CheckConstraint(check=models.Q(('recipient_groups__gte', 0), ('segments__gte', 0), _connector='OR'), name='manager_email_recipientgroups_or_segment'),
        ),
    ]
