# Generated by Django 3.1.12 on 2022-01-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_auto_20210915_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='recurrence',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Never'), (1, 'Daily'), (2, 'Weekly'), (4, 'Monthly')], default=0, help_text='If and how often the email will be resent.', null=True),
        ),
    ]
