# Generated by Django 3.1.14 on 2022-04-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_campaigninstancestat'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='avg_click_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='avg_click_to_open_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='avg_open_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='avg_recipient_count',
            field=models.IntegerField(default=0),
        ),
    ]
