# Generated by Django 3.1.14 on 2022-04-22 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_auto_20220422_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigninstancestat',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='manager.instance'),
        ),
    ]
